name: Build & Push SkyWash image

on:
  push:
    branches: [main]

env:
  IMAGE: ${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/skywash:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: read }
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build -t $IMAGE .

      - name: Login to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_URL }} \
             -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Push
        run: docker push $IMAGE
