apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "incommon"
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      -  {{ .Values.app.fqdn }}
      secretName: {{ .Values.app.name }}-tls
  rules:
    - host: {{ .Values.app.fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}  
                port:
                  number: {{ .Values.app.container.port }}
