apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.app.name }}  
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports: 
    - port: {{ .Values.app.container.port }}
      targetPort: {{ .Values.app.container.port }}
  type: ClusterIP
